SET ALLUSERSPROFILE=E:\ProgramData
SET APPDATA=E:\Users\Javier\AppData\Roaming
SET asl.log=Destination=file
SET CLASSPATH=E:\servers\MQ\java\lib\com.ibm.mqjms.jar;E:\servers\MQ\java\lib\com.ibm.mq.jar
SET COBPATH=P:\SDP\Lib
SET CommonProgramFiles=E:\Program Files\Common Files
SET CommonProgramFiles(x86)=E:\Program Files (x86)\Common Files
SET CommonProgramW6432=E:\Program Files\Common Files
SET COMPUTERNAME=DAMIEN
SET ComSpec=E:\Windows\system32\cmd.exe
SET FP_NO_HOST_CHECK=NO
SET HOMEDRIVE=E:
SET HOMEPATH=\Users\Javier
SET INCLUDE=E:\servers\MQ\tools\c\include;E:\servers\MQ\tools\cplus\include
SET JAVA_HOME=E:\SDK\Java\JDK
SET LIB=E:\servers\MQ\tools\lib64;E:\servers\MQ\tools\lib
SET LOCALAPPDATA=E:\Users\Javier\AppData\Local
SET LOGONSERVER=\\DAMIEN
SET MQ_FILE_PATH=E:\servers\MQ
SET MQ_JAVA_DATA_PATH=E:\ProgramData\IBM\MQ
SET MQ_JAVA_INSTALL_PATH=E:\servers\MQ\java
SET MQ_JAVA_LIB_PATH=E:\servers\MQ\java\lib64;E:\servers\MQ\java\lib
SET MQ_JRE_PATH=E:\servers\MQ\java\jre
SET NUMBER_OF_PROCESSORS=4
SET OS=Windows_NT
SET Path=P:\SDP\bin;E:\SDK\COBOL\VS2012\bin;E:\servers\MQ\java\lib;E:\servers\MQ\java\lib64;E:\ProgramData\Oracle\Java\javapath;E:\Windows\system32;E:\Windows;E:\Windows\System32\Wbem;E:\Windows\System32\WindowsPowerShell\v1.0\;E:\Program Files (x86)\Intel\OpenCL SDK\2.0\bin\x86;E:\Program Files (x86)\Intel\OpenCL SDK\2.0\bin\x64;E:\Program Files\Calibre2\;E:\Program Files\MATLAB\R2013b\runtime\win64;E:\Program Files\MATLAB\R2013b\bin;E:\Program Files\MATLAB\R2013b\polyspace\bin;E:\Program Files\Microsoft Windows Performance Toolkit\;E:\Program Files (x86)\Skype\Phone\;E:\SDK\Maven\bin;E:\Program Files (x86)\Windows Kits\10\Windows Performance Toolkit\;E:\Users\Javier\.dnx\bin;E:\Program Files\Microsoft DNX\Dnvm\;E:\Program Files\Microsoft SQL Server\120\Tools\Binn\;E:\Program Files (x86)\nodejs\;E:\servers\MQ\bin64;E:\servers\MQ\bin;E:\servers\MQ\tools\c\samples\bin;C:\des\MikTex\miktex\bin\x64\;P:\bin;E:\servers\mysql\bin;E:\Program Files (x86)\IDM Computer Solutions\UltraEdit\;E:\Users\Javier\AppData\Roaming\npm
SET PATHEXT=.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC
SET PROCESSOR_ARCHITECTURE=AMD64
SET PROCESSOR_IDENTIFIER=Intel64 Family 6 Model 58 Stepping 9, GenuineIntel
SET PROCESSOR_LEVEL=6
SET PROCESSOR_REVISION=3a09
SET ProgramData=E:\ProgramData
SET ProgramFiles=E:\Program Files
SET ProgramFiles(x86)=E:\Program Files (x86)
SET ProgramW6432=E:\Program Files
SET PROMPT=$P$G
SET PSModulePath=E:\Windows\system32\WindowsPowerShell\v1.0\Modules\
SET PUBLIC=E:\Users\Public
SET SESSIONNAME=Console
SET SystemDrive=E:
SET SystemRoot=E:\Windows
SET TEMP=C:\Temp
SET TMP=C:\tmp
SET USERDOMAIN=Damien
SET USERNAME=Javier
SET USERPROFILE=E:\Users\Javier
SET VBOX_MSI_INSTALL_PATH=E:\Program Files\Oracle\VirtualBox\
SET VS100COMNTOOLS=E:\Program Files (x86)\Microsoft Visual Studio 10.0\Common7\Tools\
SET VS110COMNTOOLS=E:\SDK\Windows\VS2012\Common7\Tools\
SET VS140COMNTOOLS=E:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\Tools\
SET windir=E:\Windows
SET windows_tracing_flags=3
SET windows_tracing_logfile=E:\BVTBin\Tests\installpackage\csilogfile.log
